/**
 * Fixture camera provider: the first `camera` tool call previews and then publishes one doorbell
 * press with a synthetic flat-colour frame and waits until the watch records its classified notice
 * as delivered, so the classification Session binds to the child replay script and the tool reads a
 * settled history. Notices become workspace files instead of Discord messages. No Ring account or
 * network is used.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { CameraDeviceId, CameraEventId, CameraService } from '@deepseek-ai/dsh-camera'

/** 21:00 in Phoenix on 2026-09-25, inside the default night window. */
export const OCCURRED_AT = Date.UTC(2026, 8, 26, 4, 0)

/** 32x24 flat grey-blue JPEG generated by sharp; it depicts nothing. */
const FRAME = Uint8Array.from(Buffer.from(
  '/9j/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7'
  + 'Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAAYACADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAU'
  + 'EAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdAVJQAAAAAH//2Q==',
  'base64',
))

export default class SnapshotCamera extends CameraService {
  static inject = ['attachments']

  constructor(ctx) {
    super(ctx)
    let fired = false
    let markDelivered
    const delivered = new Promise((resolve) => { markDelivered = resolve })
    ctx.on('domain/changed', (change) => {
      if (change.domain === 'camera_watch' && change.operation === 'put' && change.value.delivery === 'delivered') markDelivered()
    })
    ctx.on('camera/notice', async (notice) => {
      const dir = join(process.cwd(), 'delivered', notice.channelId)
      await mkdir(dir, { recursive: true })
      await writeFile(join(dir, `${notice.id.replaceAll(':', '-')}.md`),
        `${notice.text}\n\nImage: ${notice.image?.name ?? 'none'} (${notice.image?.mediaType ?? 'none'})\n`)
      return true
    })
    ctx.on('tools/pre-execute', async (exec, next) => {
      if (exec.name === 'camera' && !fired) {
        fired = true
        const [attachment] = await ctx.attachments.saveImages([{ data: FRAME, mediaType: 'image/jpeg', name: 'front-door-1.jpg' }])
        const frame = { attachment, offsetMs: 0, source: 'snapshot' }
        const identity = { id: CameraEventId('ring-101-5150'), deviceId: CameraDeviceId('front-door'), kind: 'ding', occurredAt: OCCURRED_AT }
        await this.publishPreview({ ...identity, frame })
        await this.publish({ ...identity, frames: [frame] })
        await delivered
      }
      return next()
    })
  }

  devices() {
    return [{ id: CameraDeviceId('front-door'), label: 'Front door' }, { id: CameraDeviceId('garage'), label: 'Garage' }]
  }
}
